import Head from 'next/head'
import Image from 'next/image'
import {Roboto, Roboto_Condensed} from 'next/font/google'
import styles from '@/styles/Home.module.css'
import React, {ReactNode, useState} from 'react'
import Introduction from '../rcs/Introduction.js'
import ReactDOM from "react-dom/client";
import {AudioRecorder} from 'react-audio-voice-recorder';
import {CssBaseline, Drawer, Grid, Modal, Paper, Typography,} from "@mui/material";
import {Box} from "@mui/system";
import Button from '@mui/material/Button';

import List from '@mui/material/List';
import Divider from '@mui/material/Divider';
import ListItem from '@mui/material/ListItem';
import ListItemButton from '@mui/material/ListItemButton';
import ListItemIcon from '@mui/material/ListItemIcon';
import ListItemText from '@mui/material/ListItemText';
import InboxIcon from '@mui/icons-material/MoveToInbox';
import MailIcon from '@mui/icons-material/Mail';
import ArrowForwardIosTwoToneIcon from '@mui/icons-material/ArrowForwardIosTwoTone';
import SettingsIcon from '@mui/icons-material/Settings';
import CustomDrawer from "@/rcs/CustomDrawer";
import SettingsModal from "@/rcs/SettingsModal";

const robotoCon = Roboto_Condensed({subsets: ['latin'], weight: '400'});


export default function Home() {
    const [open, setOpen] = useState(false);
    const handleOpen = () => setOpen(true);
    const handleClose = () => setOpen(false);


    return (
        <div className={`${robotoCon.className}  customBackgr`}>
            <div className="customBackgr">
                <Head>
                    <title>Whisper x ChatGpt</title>
                    <meta name="description" content="Generated by create next app"/>
                    <meta name="viewport" content="width=device-width, initial-scale=1"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>

                <Introduction/>

                <div id="audio-recorder-grid">
                    <AudioRecorder/>
                </div>

                <CustomDrawer/>

                <div className="alignSettingsButton">
                    <Button onClick={handleOpen} startIcon={<SettingsIcon sx={{fontSize: '2.5rem !important'}}/>}
                             className="settingsButton"></Button>
                </div>

                <SettingsModal open={open} onClose={handleClose}/>

                <Box sx={{paddingX: '5rem'}}>
                    <div className={`${styles.gridContainer} ${styles.gridScrollbar}`}>
                        <Grid container spacing={1} justifyContent={"center"} alignItems={"center"} xs={12}>
                            <Grid item container alignItems={"center"} justifyContent={"center"} xs={10}
                                  direction={"column"}>
                                <Grid item justifyContent={"center"} pt={2}>
                                    <Typography variant={"h1"}>Hello there</Typography>
                                </Grid>
                                <Grid item justifyContent={"center"} p={10}>
                                    <div className={styles.description}>
                                        <Typography fontSize={'2rem'}>
                                            Why do we use it?
                                            It is a long established fact that a reader will be distracted by the
                                            readable
                                            content of a page when looking at its layout. The point of using Lorem Ipsum
                                            is
                                            that it has a more-or-less normal distribution of letters, as opposed to
                                            using
                                            'Content here, content here', making it look like readable English. Many
                                            desktop
                                            publishing packages and web page editors now use Lorem Ipsum as their
                                            default
                                            model text, and a search for 'lorem ipsum' will uncover many web sites still
                                            in
                                            their infancy. Various versions have evolved over the years, sometimes by
                                            accident, sometimes on purpose (injected humour and the like).

                                            Where does it come from?
                                            Contrary to popular belief, Lorem Ipsum is not simply random text. It has
                                            roots
                                            in a piece of classical Latin literature from 45 BC, making it over 2000
                                            years
                                            old. Richard McClintock, a Latin professor at Hampden-Sydney College in
                                            Virginia, looked up one of the more obscure Latin words, consectetur, from a
                                            Lorem Ipsum passage, and going through the cites of the word in classical
                                            literature, discovered the undoubtable source. Lorem Ipsum comes from
                                            sections
                                            1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good
                                            and
                                            Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of
                                            ethics, very popular during the Renaissance. The first line of Lorem Ipsum,
                                            "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

                                            The standard chunk of Lorem Ipsum used since the 1500s is reproduced below
                                            for
                                            those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et
                                            Malorum" by Cicero are also reproduced in their exact original form,
                                            accompanied
                                            by English versions from the 1914 translation by H. Rackham.
                                        </Typography>
                                    </div>
                                </Grid>

                                <Grid item justifyContent={"center"} p={10}>

                                    <div className={styles.description}>
                                        Why do we use it?
                                        It is a long established fact that a reader will be distracted by the readable
                                        content of a page when looking at its layout. The point of using Lorem Ipsum is
                                        that it has a more-or-less normal distribution of letters, as opposed to using
                                        'Content here, content here', making it look like readable English. Many desktop
                                        publishing packages and web page editors now use Lorem Ipsum as their default
                                        model text, and a search for 'lorem ipsum' will uncover many web sites still in
                                        their infancy. Various versions have evolved over the years, sometimes by
                                        accident, sometimes on purpose (injected humour and the like).


                                        Where does it come from?
                                        Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots
                                        in a piece of classical Latin literature from 45 BC, making it over 2000 years
                                        old. Richard McClintock, a Latin professor at Hampden-Sydney College in
                                        Virginia, looked up one of the more obscure Latin words, consectetur, from a
                                        Lorem Ipsum passage, and going through the cites of the word in classical
                                        literature, discovered the undoubtable source. Lorem Ipsum comes from sections
                                        1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and
                                        Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of
                                        ethics, very popular during the Renaissance. The first line of Lorem Ipsum,
                                        "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

                                        The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for
                                        those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et
                                        Malorum" by Cicero are also reproduced in their exact original form, accompanied
                                        by English versions from the 1914 translation by H. Rackham.
                                    </div>
                                </Grid>


                                <Grid item justifyContent={"center"} p={10}>
                                    <div className={styles.description}>
                                        Why do we use it?
                                        It is a long established fact that a reader will be distracted by the readable
                                        content of a page when looking at its layout. The point of using Lorem Ipsum is
                                        that it has a more-or-less normal distribution of letters, as opposed to using
                                        'Content here, content here', making it look like readable English. Many desktop
                                        publishing packages and web page editors now use Lorem Ipsum as their default
                                        model text, and a search for 'lorem ipsum' will uncover many web sites still in
                                        their infancy. Various versions have evolved over the years, sometimes by
                                        accident, sometimes on purpose (injected humour and the like).


                                        Where does it come from?
                                        Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots
                                        in a piece of classical Latin literature from 45 BC, making it over 2000 years
                                        old. Richard McClintock, a Latin professor at Hampden-Sydney College in
                                        Virginia, looked up one of the more obscure Latin words, consectetur, from a
                                        Lorem Ipsum passage, and going through the cites of the word in classical
                                        literature, discovered the undoubtable source. Lorem Ipsum comes from sections
                                        1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and
                                        Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of
                                        ethics, very popular during the Renaissance. The first line of Lorem Ipsum,
                                        "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

                                        The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for
                                        those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et
                                        Malorum" by Cicero are also reproduced in their exact original form, accompanied
                                        by English versions from the 1914 translation by H. Rackham.
                                    </div>
                                </Grid>

                                <Grid item justifyContent={"center"} p={10}>
                                    <div className={styles.description}>
                                        Why do we use it?
                                        It is a long established fact that a reader will be distracted by the readable
                                        content of a page when looking at its layout. The point of using Lorem Ipsum is
                                        that it has a more-or-less normal distribution of letters, as opposed to using
                                        'Content here, content here', making it look like readable English. Many desktop
                                        publishing packages and web page editors now use Lorem Ipsum as their default
                                        model text, and a search for 'lorem ipsum' will uncover many web sites still in
                                        their infancy. Various versions have evolved over the years, sometimes by
                                        accident, sometimes on purpose (injected humour and the like).


                                        Where does it come from?
                                        Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots
                                        in a piece of classical Latin literature from 45 BC, making it over 2000 years
                                        old. Richard McClintock, a Latin professor at Hampden-Sydney College in
                                        Virginia, looked up one of the more obscure Latin words, consectetur, from a
                                        Lorem Ipsum passage, and going through the cites of the word in classical
                                        literature, discovered the undoubtable source. Lorem Ipsum comes from sections
                                        1.10.32 and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and
                                        Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of
                                        ethics, very popular during the Renaissance. The first line of Lorem Ipsum,
                                        "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.

                                        The standard chunk of Lorem Ipsum used since the 1500s is reproduced below for
                                        those interested. Sections 1.10.32 and 1.10.33 from "de Finibus Bonorum et
                                        Malorum" by Cicero are also reproduced in their exact original form, accompanied
                                        by English versions from the 1914 translation by H. Rackham.

                                        Where can I get some?
                                        There are many variations of passages of Lorem Ipsum available, but the majority
                                        have suffered alteration in some form, by injected humour, or randomised words
                                        which don't look even slightly believable. If you are going to use a passage of
                                        Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the
                                        middle of text. All the Lorem Ipsum generators on the Internet tend to repeat
                                        predefined chunks as necessary, making this the first true generator on the
                                        Internet. It uses a dictionary of over 200 Latin words, combined with a handful
                                        of model sentence structures, to generate Lorem Ipsum which looks reasonable.
                                        The generated Lorem Ipsum is therefore always free from repetition, injected
                                        humour, or non-characteristic words etc.
                                    </div>
                                </Grid>


                            </Grid>
                        </Grid>
                    </div>
                </Box>


            </div>
        </div>
    )

}
